name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-dockerhub-username/my-nginx-app:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Copy SSH key
      run: echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
      shell: bash

    - name: Change permission for SSH key
      run: chmod 400 key.pem
      shell: bash

    - name: Run SSH command to deploy Docker container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          docker pull your-dockerhub-username/my-nginx-app:latest
          docker stop my-nginx-app || true
          docker rm my-nginx-app || true
          docker run -d -p 80:80 --name my-nginx-app your-dockerhub-username/my-nginx-app:latest
        EOF
      shell: bash
